### ISSUE TITLE
Looking for a team?

### ISSUE THREAD

**Issue by JoaoLucasViegas** [kevlamity/PomodoroTimer#1]
I was trying to find some base code of timer on github to try a "pomodoro project". I only realized now that your project is empty/blank.

I ain't very skilled with JS(more of a python/java guy) but if this is any type of "study" project, we can team up and work together on this one (I'm just asking, we are both trying to do the same project, why not use some extra help? - these are my thoughts on it).

My idea for my "pomodoro timer" is about a page or even an OS software(native system) that the user setups the rest and active time and how many cycles it wants to repeat till turn off; Then the user triggers the timer and the timer would've automatically manage all the "cycles" between rest and active (also, it should stores the last "setup" config the users did).
My main focus were about how to do the graphics, make it with a simple but clean design to use; No background image stuff that creates noise at the page/screen or any big effects(things splashing or shinning buttons). Just being straightforward, doing what users expect it to be, doing what is intended to do (no gibberish at all for the user).

_I got some "inspiration" from activity watch which is a free "activity monitor" that shows you all that you've been doing with your time, being a weekly, daily or even in a month. Simple UI, straightforward functionalities and very useful if the user keeps track of._

_Screenshot from their website if you never seen it before:_ <img src="https://activitywatch.net/img/screenshots/screenshot-v0.9.3-activity.png">

**Comment by kevlamity** [comment]
Hi,

I am creating this project for a frontend developer test, not really a
personal project that I am interested in pursuing, thanks!

Kind regards,
Kevin
